-- MySQL Script generated by MySQL Workbench
-- Thu Feb  6 17:00:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PcD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PcD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PcD` DEFAULT CHARACTER SET utf8 ;
USE `PcD` ;

-- -----------------------------------------------------
-- Table `PcD`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PcD`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `role` ENUM('paciente', 'profissional', 'admin') NOT NULL,
  `data_criacao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PcD`.`profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PcD`.`profissional` (
  `id_profissional` INT NOT NULL AUTO_INCREMENT,
  `registro_profissional` VARCHAR(50) NOT NULL,
  `biografia` LONGTEXT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_profissional`),
  INDEX `fk_profissional_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_profissional_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `PcD`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PcD`.`transtorno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PcD`.`transtorno` (
  `id_transtorno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `diretrizes_tratamento` LONGTEXT NOT NULL,
  PRIMARY KEY (`id_transtorno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PcD`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PcD`.`equipe` (
  `id_equipe` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  PRIMARY KEY (`id_equipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PcD`.`artigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PcD`.`artigo` (
  `id_artigo` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `conteudo` LONGTEXT NOT NULL,
  `data_publicacao` DATE NOT NULL,
  `transtorno_id_transtorno` INT NOT NULL,
  `profissional_id_profissional` INT NOT NULL,
  PRIMARY KEY (`id_artigo`),
  INDEX `fk_artigo_transtorno1_idx` (`transtorno_id_transtorno` ASC) VISIBLE,
  INDEX `fk_artigo_profissional1_idx` (`profissional_id_profissional` ASC) VISIBLE,
  CONSTRAINT `fk_artigo_transtorno1`
    FOREIGN KEY (`transtorno_id_transtorno`)
    REFERENCES `PcD`.`transtorno` (`id_transtorno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artigo_profissional1`
    FOREIGN KEY (`profissional_id_profissional`)
    REFERENCES `PcD`.`profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PcD`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PcD`.`agendamento` (
  `id_agendamento` INT NOT NULL AUTO_INCREMENT,
  `data_hora` DATETIME NOT NULL,
  `status` ENUM('agendado', 'concluido', 'cancelado') NOT NULL,
  `notas` TEXT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `profissional_id_profissional` INT NOT NULL,
  PRIMARY KEY (`id_agendamento`),
  INDEX `fk_agendamento_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_agendamento_profissional1_idx` (`profissional_id_profissional` ASC) VISIBLE,
  CONSTRAINT `fk_agendamento_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `PcD`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendamento_profissional1`
    FOREIGN KEY (`profissional_id_profissional`)
    REFERENCES `PcD`.`profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PcD`.`TopicoForum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PcD`.`TopicoForum` (
  `id_topico` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NULL,
  `conteudo` TEXT NULL,
  `data_criacao` TIMESTAMP NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_topico`),
  INDEX `fk_TopicoForum_usuario_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_TopicoForum_usuario`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `PcD`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PcD`.`RespostaForum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PcD`.`RespostaForum` (
  `id_resposta` INT NOT NULL AUTO_INCREMENT,
  `conteudo` TEXT NULL,
  `data_criacao` TIMESTAMP NULL,
  `usuario_id_usuario` INT NOT NULL,
  `TopicoForum_id_topico` INT NOT NULL,
  PRIMARY KEY (`id_resposta`),
  INDEX `fk_RespostaForum_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_RespostaForum_TopicoForum1_idx` (`TopicoForum_id_topico` ASC) VISIBLE,
  CONSTRAINT `fk_RespostaForum_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `PcD`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RespostaForum_TopicoForum1`
    FOREIGN KEY (`TopicoForum_id_topico`)
    REFERENCES `PcD`.`TopicoForum` (`id_topico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PcD`.`especializacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PcD`.`especializacao` (
  `profissional_id_profissional` INT NOT NULL,
  `transtorno_id_transtorno` INT NOT NULL,
  PRIMARY KEY (`profissional_id_profissional`, `transtorno_id_transtorno`),
  INDEX `fk_profissional_has_transtorno_transtorno1_idx` (`transtorno_id_transtorno` ASC) VISIBLE,
  INDEX `fk_profissional_has_transtorno_profissional1_idx` (`profissional_id_profissional` ASC) VISIBLE,
  CONSTRAINT `fk_profissional_has_transtorno_profissional1`
    FOREIGN KEY (`profissional_id_profissional`)
    REFERENCES `PcD`.`profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profissional_has_transtorno_transtorno1`
    FOREIGN KEY (`transtorno_id_transtorno`)
    REFERENCES `PcD`.`transtorno` (`id_transtorno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PcD`.`membroEquipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PcD`.`membroEquipe` (
  `equipe_id_equipe` INT NOT NULL,
  `profissional_id_profissional` INT NOT NULL,
  PRIMARY KEY (`equipe_id_equipe`, `profissional_id_profissional`),
  INDEX `fk_equipe_has_profissional_profissional1_idx` (`profissional_id_profissional` ASC) VISIBLE,
  INDEX `fk_equipe_has_profissional_equipe1_idx` (`equipe_id_equipe` ASC) VISIBLE,
  CONSTRAINT `fk_equipe_has_profissional_equipe1`
    FOREIGN KEY (`equipe_id_equipe`)
    REFERENCES `PcD`.`equipe` (`id_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipe_has_profissional_profissional1`
    FOREIGN KEY (`profissional_id_profissional`)
    REFERENCES `PcD`.`profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
